# generate UserDataExtraJournals.ts
echo > typescript/UserDataExtraJournals.ts
echo "// Generated by generate.sh, do not edit this file manually" >> typescript/UserDataExtraJournals.ts
echo "let UserDataExtraJournals = " >> typescript/UserDataExtraJournals.ts
cat json/UserDataExtraJournals.json >> typescript/UserDataExtraJournals.ts
echo ';' >> typescript/UserDataExtraJournals.ts

cat typescript/*.ts > temp/compiled.ts
tsc temp/compiled.ts
cat temp/compiled.js > ../www/deploy/assets/extras/typescript-compiled-app.js