class DataHelper {
    public static savedJournalsMasterDataArray: Array<TSJournal> = [];
    public static savedJournalsMasterDataDictionary: any = {};

    public static populateSjmdArrayToDictionary() {
        this.savedJournalsMasterDataDictionary = {}; // reset.
        this.savedJournalsMasterDataArray.forEach(thisJournal => {
            this.savedJournalsMasterDataDictionary[thisJournal.journal_id] = thisJournal;
        });
    }
}
class TSJournal {
	journal_id: string;
	journal_name: string;
	url: string;
	issn: string;
	issne: string;
	scopus_sourceid: string;
	scopus_coverage: string;
}
class UIJournalSelectorController {
    public static selectedJournalIdsForSearch: string[] = [];
    
}
class UsefulHelper {
	public static nvl(value: any, fallbackValue: any) {
		return typeof value !== 'undefined' && value != null
			? value
			: fallbackValue;
	}
}

// Generated by generate.sh, do not edit this file manually
let UserDataExtraJournals = 
[
	{
		"journal_id": "SCOPUS_22486",
		"journal_name": "R and D Management",
		"url": "https://onlinelibrary.wiley.com/journal/14679310",
		"issn": "0033-6807",
		"issne": "1467-9310",
		"scopus_sourceid": "22486",
		"scopus_coverage": "1970-ongoing"
	},
	{
		"journal_id": "SCOPUS_28945",
		"journal_name": "Industrial and Corporate Change",
		"url": "https://academic.oup.com/icc",
		"issn": "0960-6491",
		"issne": "1464-3650",
		"scopus_sourceid": "28945",
		"scopus_coverage": "1992-ongoing"
	}
];
